scheduler/views/worker_views.py
from datetime import date, datetime

from flask import Blueprint, flash, g, redirect, render_template, request, url_for

from scheduler import db
from scheduler.forms import WorkerForm
from scheduler.models import DosuSess, DosuType, Patient, User, Worker

bp = Blueprint("worker", __name__, url_prefix="/worker")


@bp.route("/list")
def worker_list():
    workers = db.session.execute(
        db.select(Worker).order_by(Worker.available, Worker.id)
    ).scalars()
    return render_template("worker/list.html", workers=workers)


@bp.route("/create", methods=["GET", "POST"])
def worker_create():
    if not g.user or g.user.privilege != 5:
        flash("권한이 없습니다")
        return redirect(url_for("worker.worker_list"))

    form = WorkerForm()
    if request.method == "POST" and form.validate_on_submit():
        user_id = form.user_id.data
        name = form.name.data
        room = int(form.room.data)
        available = form.available.data == "yes"

        try:
            worker = Worker(
                user_id=user_id,
                name=name,
                room=room,
                available=available,
            )
            db.session.add(worker)
            db.session.commit()
            return redirect(url_for("worker.worker_detail", id=worker.id))
        except Exception as e:
            db.session.rollback()
            flash(f"Worker: Failed creating {name}: {e}")

    users = db.session.execute(db.select(User).filter_by(available=True)).scalars()
    return render_template("worker/form.html", form=form, users=users)


@bp.route("/update/<int:id>", methods=("GET", "POST"))
def worker_update(id):
    if not g.user or g.user.privilege != 5:
        flash("권한이 없습니다")
        return redirect(url_for("worker.worker_list"))

    worker = db.get_or_404(Worker, id)
    if request.method == "POST":
        form = WorkerForm()
        if form.validate_on_submit():
            worker.user_id = form.user_id.data
            worker.name = form.name.data
            worker.room = form.room.data
            worker.available = form.available.data == "yes"
            try:
                db.session.commit()
                return redirect(url_for("worker.worker_detail", id=worker.id))
            except Exception as e:
                db.session.rollback()
                flash(f"Worker: Failed updating {worker.name}: {e}")

    form = WorkerForm(obj=worker)
    users = db.session.execute(db.select(User).filter_by(available=True)).scalars()
    return render_template("worker/form.html", form=form, users=users)


@bp.route("/<int:id>")
def worker_detail(id):
    worker = db.get_or_404(Worker, id)
    kw = request.args.get("kw", type=str, default="")
    page = request.args.get("page", type=int, default=1)

    start_date = datetime.strptime(
        request.args.get(
            "start_date",
            default=date.today()
            .replace(month=date.today().month - 1)
            .strftime("%Y-%m-%d"),
        ),
        "%Y-%m-%d",
    )
    end_date = datetime.strptime(
        request.args.get(
            "end_date",
            default=date.today()
            .replace(month=date.today().month + 1)
            .strftime("%Y-%m-%d"),
        ),
        "%Y-%m-%d",
    )

    dosusess_list = (
        db.select(DosuSess)
        .filter(
            DosuSess.worker_id == id,
            DosuSess.dosusess_date.between(start_date, end_date),
        )
        .order_by(DosuSess.dosusess_date.desc())
    )

    if kw:
        search = "%%{}%%".format(kw)
        dosusess_list = (
            dosusess_list.join(DosuSess.patient)
            .join(DosuSess.dosutype)
            .filter(
                DosuSess.note.ilike(search)
                | DosuSess.status.ilike(search)
                | DosuSess.dosusess_date.ilike(search)
                | Patient.mrn.ilike(search)
                | Patient.name.ilike(search)
                | DosuType.name.ilike(search)
            )
            .distinct()
        )

    pagination = db.paginate(
        dosusess_list,
        page=page,
        per_page=10,
    )

    return render_template(
        "worker/detail.html",
        worker=worker,
        pagination=pagination,
        kw=kw,
        start_date=start_date.strftime("%Y-%m-%d"),
        end_date=end_date.strftime("%Y-%m-%d"),
    )


@bp.route("/delete/<int:id>", methods=["GET", "POST"])
def worker_delete(id):
    if not g.user or g.user.privilege != 5:
        flash("권한이 없습니다")
        return redirect(url_for("worker.worker_list"))

    worker = db.get_or_404(Worker, id)
    if request.method == "POST":
        confirm = request.form.get("confirm", None)
        if len(worker.dosusess_set) == 0 or confirm == "yes":
            db.session.delete(worker)
            db.session.commit()
            flash("Success deleting the worker.")
        else:
            flash("The worker has dosu session records")
        return redirect(url_for("worker.worker_list"))
    # If there are dosu sessions, but the user has privilege 5, ask for confirmation
    need_confirm = False
    if len(worker.dosusess_set) > 0:
        need_confirm = True

    return render_template(
        "delete.html",
        entity_type="Worker",
        entity_name=worker.name,
        entity_id=worker.id,
        entity_delete_url="worker.worker_delete",
        entity_list_url="worker.worker_list",
        need_confirm=need_confirm,
    )

scheduler/templates/worker/detail.html
{% extends "base.html" %}
{% block title %}치료사 세부 정보{% endblock %}
{% block content %}
    <h1 class="my-4">치료사 세부 정보</h1>
    <div class="col-8 mb-3">
        <table class="table table-striped text-center align-middle">
            <thead class="thead-dark">
                <tr>
                    <th>번 호</th>
                    <th>유 저</th>
                    <th>이 름</th>
                    <th>치료실</th>
                    <th>상 태</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ worker.id }}</td>
                    <td>{{ worker.user.username }}</td>
                    <td>{{ worker.name }}</td>
                    <td>{{ worker.room }}</td>
                    <td>{{ '활성' if worker.available else '비활성' }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr class="table-group-divider my-5">
    <div class="container my-3">
        <div class="row justify-content-between mb-4">
            <h3 class="col-2 text-center">도수 리스트</h3>
            <!-- Search dates -->
            <div class="col-3">
                <div class="input-group">
                    <span class="input-group-text">조회시작</span>
                    <input type="date"
                           class="form-control"
                           id="startDate"
                           value="{{ start_date }}">
                </div>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <span class="input-group-text">조회종료</span>
                    <input type="date" class="form-control" id="endDate" value="{{ end_date }}">
                </div>
            </div>
            <!-- Search content -->
            <div class="col-4">
                <div class="input-group">
                    <input type="text" class="form-control" id="kwInput" value="{{ kw or '' }}">
                    <button type="button" class="btn btn-outline-secondary" id="searchBtn">Search</button>
                </div>
            </div>
        </div>
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">번 호</th>
                    <th scope="col">날 짜</th>
                    <th scope="col">상 태</th>
                    <th scope="col">환자번호</th>
                    <th scope="col">환 자</th>
                    <th scope="col">도수타입</th>
                    <th scope="col" class="max-width">노 트</th>
                </tr>
            </thead>
            <tbody>
                {% if pagination %}
                    {% for dosusess in pagination %}
                        <tr class="text-center align-middle">
                            <td>{{ pagination.total - ((pagination.page-1) * pagination.per_page) -loop.index0 }}</td>
                            <td>{{ dosusess.dosusess_date }}</td>
                            <td>{{ dosusess.status }}</td>
                            <td>{{ dosusess.patient.mrn }}</td>
                            <td>{{ dosusess.patient.name }}</td>
                            <td>{{ dosusess.dosutype.name }}</td>
                            <td>
                                <pre class="limited-text">{{ dosusess.note }}</pre>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colepan="3">해당 기록이 없습니다</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <!-- Paging -->
        <nav aria-label="...">
            <ul class="pagination justify-content-center">
                {% if pagination.has_prev %}
                    <li class="page-item">
                        <a href="#" class="page-link" data-page="{{ pagination.prev_num }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                {% endif %}
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page != pagination.page %}
                            <li class="page-item">
                                <a href="#" class="page-link" data-page="{{ page }}">{{ page }}</a>
                            </li>
                        {% else %}
                            <li class="page-item active">
                                <span class="page-link">{{ page }}</span>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="disabled">
                            <span class="page-link">…</span>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if pagination.has_next %}
                    <li class="page-item">
                        <a href="#" class="page-link" data-page="{{ pagination.next_num }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Next</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <form id="searchForm"
          method="get"
          action="{{ url_for("worker.worker_detail", id=worker.id) }}">
        <input type="hidden" id="kwFormInput" name="kw" value="{{ kw or '' }}">
        <input type="hidden" id="sdInput" name="start_date" value="{{ start_date }}">
        <input type="hidden" id="edInput" name="end_date" value="{{ end_date }}">
        <input type="hidden" id="pageFormInput" name="page" value="{{ page }}">
    </form>
{% endblock %}
{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const pageLinkEls = document.querySelectorAll(".page-link");
            const searchFormEl = document.getElementById("searchForm");
            const kwInputEl = document.getElementById("kwInput");
            const kwInputFormEl = document.getElementById("kwFormInput");
            const startDateInputEl = document.getElementById("startDate");
            const endDateInputEl = document.getElementById("endDate");
            const startDateInputFormEl = document.getElementById("sdInput");
            const endDateInputFormEl = document.getElementById("edInput");
            const pageInputFormEl = document.getElementById("pageFormInput");
            const searchBtnEl = document.getElementById("searchBtn");

            pageLinkEls.forEach(function(pageLinkEl){
                pageLinkEl.addEventListener('click', function(e) {
                    e.preventDefault();
                    pageInputFormEl.value = this.getAttribute('data-page');
                    searchFormEl.submit();
                });
            });

            const searchFn = function(e) {
                e.preventDefault();
                const searchKw = kwInputEl.value;
                kwInputFormEl.value = searchKw;
                startDateInputFormEl.value = startDateInputEl.value;
                endDateInputFormEl.value = endDateInputEl.value;
                pageInputFormEl.value = 1;
                searchFormEl.submit();
            };
            searchBtnEl.addEventListener('click', searchFn);
            kwInputEl.addEventListener('keydown', function(e) {
                if (e.key === 'Enter') {
                    searchFn(e);
                }
            });

        });
    </script>
{% endblock %}

scheduler/templates/worker/form.html
{% extends "base.html" %}
{% block title %}Create/Update Worker{% endblock %}
{% block content %}
    <h1 class="my-4">{{ 'Update Worker' if form.name.data else 'Create New Worker' }}</h1>
    <form method="post">
        {% include "form_errors.html" %}
        {{ form.csrf_token }}
        <div class="input-group mb-3">
            <span class="input-group-text">{{ form.name.label }}</span>
            {{ form.name(class="form-control") }}
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">{{ form.room.label }}</span>
            {{ form.room(class="form-select") }}
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">{{ form.user_id.label }}</span>
            <select class="form-select" name="user_id">
                {% if form.user_id.data %}
                    <option>Choose the user</option>
                    {% for user in users %}
                        <option value="{{ user.id }}"
                                "
                                {{ 'selected' if user.id == form.user_id.data }}
                                ">{{ user.username }}</option>
                    {% endfor %}
                {% else %}
                    <option selected>Choose the user</option>
                    {% for user in users %}<option value="{{ user.id }}">{{ user.username }}</option>{% endfor %}
                {% endif %}
            </select>
        </div>
        <div class="row mb-5 align-items-center">
            <label class="col-md-2">{{ form.available.label }}</label>
            <div class="col-sm-8 btn-group" role="group">
                <input type="radio" class="btn-check" id="available_yes" name="available" value="yes" {{ 'checked' if form.available.data == 'True' or 'yes' }}>
                <label class="btn btn-outline-primary" for="available_yes">활성</label>
                <input type="radio" class="btn-check" id="available_no" name="available" value="no" {{ 'checked' if form.available.data == 'False' }}>
                <label class="btn btn-outline-secondary" for="available_no">비활성</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
        <a class="btn btn-secondary" href="{{ url_for("worker.worker_list") }}">취소</a>
    </form>
{% endblock %}

scheduler/templates/worker/list.html
{% extends "base.html" %}
{% block title %}Worker List{% endblock %}
{% block content %}
    <h1 class="my-4">치료사 리스트</h1>
    <a class="btn btn-primary mb-3"
       href="{{ url_for("worker.worker_create") }}">Create New Worker</a>
    <table class="table table-striped text-center">
        <thead>
            <tr>
                <th scope="col">이 름</th>
                <th scope="col">유 저</th>
                <th scope="col">치료실</th>
                <th scope="col">활성상태</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for worker in workers %}
                <tr class="text-center align-middle">
                    <td>
                        <a href="{{ url_for('worker.worker_detail', id=worker.id) }}">{{ worker.name }}</a>
                    </td>
                    <td>{{ worker.user.username }}</td>
                    <td>{{ worker.room }}</td>
                    <td>{{ worker.available }}</td>
                    <td>
                        <a class="btn btn-info btn-sm"
                           href="{{ url_for('worker.worker_update', id=worker.id) }}">수정</a>
                        <a class="btn btn-danger btn-sm"
                           href="{{ url_for('worker.worker_delete', id=worker.id) }}">삭제</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}